baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "cultural Cookbook | Spark-Y"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About Spark-Y"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Farm"
    url     = "farm"
    weight  = 3
  [[menu.nav]]
    name    = "Cookbook"
    url     = "cookbook"
    weight  = 4
  [[menu.nav]]
    name    = "Support our work"
    url     = "https://www.spark-y.org/donate"
    weight  = 5

# Site Params
[params]
  logo = "images/CookBook_Logo.png"
  logo_footer = "images/CookBook_Logo.png"
  favicon_icon = "images/CookBook_favicon_cropped.png"
  favicon_shortcut_icon = "images/CookBook_favicon_cropped.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "A youth focused non-profit"
  author = "ALifeLivedFully"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below # NOTE: you can use google forms instead
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "A garden and cookbook based on Minnesota's diverse culture's."
    tagline               = "Spark-Y and WeFarm"
    primary_button        = "Check out the farm"
    primary_button_url    = "farm"
    secondary_button      = "View the cookbook"
    secondary_button_url  = "cookbook"

  [params.cookbook]
    read_more             = "read more"

  [params.farm]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view techniques"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LETâ€™S FIX THE PLANET"
    primary_button      = "Support our work"
    primary_button_url  = "https://www.spark-y.org/donate"
    secondary_button    = "See more from Spark-Y"
    secondary_button_url = "https://www.spark-y.org/" # TODO

  [params.footer]
    params.footer.qr_print = true
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Casket Arts Building | 681 17th Ave NE, Suite 101 Minneapolis, MN 55413"
      phone   = "612-208-2273"
      email   = "info@spark-y.org"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Spark-Y"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Farm"
          url  = "farm"
        [[params.footer.sitemap.link]]
          name = "Cookbook"
          url  = "cookbook"
        [[params.footer.sitemap.link]]
          name = "Support our work"
          url  = "https://www.spark-y.org/donate"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/SparkYouthActionLabs/"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/sparkyorg/"
        [[params.footer.social.link]]
          name = "Newsletter"
          url  = "https://sparky.app.neoncrm.com/np/clients/sparky/subscribe.jsp?subscription=1"
        [[params.footer.social.link]]
          name = "Spark-Y Site"
          url  = "https://www.spark-y.org/"
      # Footer Service
      [params.footer.service]
        title       = "Spark-Y"
        description = "A youth focused non-profit based in Minnesota focused on connecting youth with the planet"
      [params.footer.back_to_top]
        description = "Back to top"
